apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: test-app
  labels:
    app: test-label-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
