apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: test-app
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
